name: Bug report
description: Report a reproducible problem
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please include enough detail to reproduce.
  - type: input
    id: version
    attributes:
      label: neewer-cli version
      placeholder: "0.1.0"
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: OS + Python
      placeholder: "Windows 11, Python 3.12"
    validations:
      required: true
  - type: textarea
    id: command
    attributes:
      label: Command used
      placeholder: "neewer-cli --preset all_on --debug"
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Config snippet (sanitized)
      render: json
  - type: textarea
    id: logs
    attributes:
      label: Debug output
      description: Include `--debug` output and remove sensitive data.
      render: text
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
